### ISSUE TITLE
Prepare release 3.26

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-smithy#1767]
### Tasks

- [x] Ensure required PRs have been merged
- [x] Test `main` on some feedstocks:
  - [x] `dav1d`: https://github.com/conda-forge/dav1d-feedstock/pull/10
    - [X] [Default conda-forge.yml (install with mamba, build with mambabuild)](https://github.com/conda-forge/dav1d-feedstock/pull/10/commits/65f90444f622681ee343148089c186f2c3288ed6)
    - [X] [Install and build use libmamba](https://github.com/conda-forge/dav1d-feedstock/pull/10/commits/c966b1b425838e87915f5af86b9809a7e0114278) + [fix](https://github.com/conda-forge/dav1d-feedstock/pull/10/commits/e96bcc00f4f56695cc5919a2b72b02fb6e2504ae) via https://github.com/conda-forge/conda-smithy/pull/1768. This doesn't solve well on macOS. We'll probably need conda-libmamba-solver 23.9.0 for this. Not a blocker!
- [X] Run `rever -c x.y.z` and check everything works
- [x] Run `rever` and [push changelog](https://github.com/conda-forge/conda-smithy/commit/ff4f6cae87bebbf00a54e5fb4c4fbf73490d5bc2) and [release](https://github.com/conda-forge/conda-smithy/releases/tag/v3.26.0)
- [x] Release package on [feedstock](https://github.com/conda-forge/conda-smithy-feedstock) - https://github.com/conda-forge/conda-smithy-feedstock/pull/260

cc @xhochy

**Comment by xhochy** [comment]
@jaimergp The current workflow is that `rever` will directly do the release directly and I don't see an option to do it as PR.

Running the local check for me works:

```
% rever -c 3.26.0
All CLI and import requirements met for authors activity
activity-check:authors:Checked activity authors
No checks needed for changelog activity
No checks needed for tag activity
All CLI and import requirements met for push_tag activity
Initialized empty Git repository in /Users/uwe/Development/conda-smithy/rever/git-have-push-perm/.git/
Switched to a new branch '__rever__'
`.pre-commit-config.yaml` config file not found. Skipping `pre-commit`.
[__rever__ (root-commit) b47c598] Checking rever permissions
Enumerating objects: 2, done.
Counting objects: 100% (2/2), done.
Writing objects: 100% (2/2), 565 bytes | 565.00 KiB/s, done.
Total 2 (delta 0), reused 0 (delta 0), pack-reused 0
remote:
remote: Create a pull request for '__rever__' on GitHub by visiting:
remote:      https://github.com/conda-forge/conda-smithy/pull/new/__rever__
remote:
To github.com:conda-forge/conda-smithy.git
 * [new branch]      __rever__ -> __rever__
To github.com:conda-forge/conda-smithy.git
 - [deleted]         __rever__
activity-check:push_tag:Checked activity push_tag
All CLI and import requirements met for ghrelease activity
GitHub login as xhochy works!
activity-check:ghrelease:Checked activity ghrelease
All CLI and import requirements met for conda_forge activity
GitHub login as xhochy works!
activity-check:conda_forge:Checked activity conda_forge
```

**Comment by jaimergp** [comment]
Ah, good, that works too. Updated item list. Let's see if Azure works now.

**Comment by jaimergp** [comment]
Ugh, found a bug. Will open a PR.
